#!/usr/bin/bash

mapfile -t logs < test_logs
declare -a programs

for record in "${logs[@]}"; do
    data=( $record )
    
    if ! [[ "${programs[*]}" == *"${data[1]}"* ]]; then
        programs+=( "${data[1]} 0 0" )
    fi

done

for program in ${!programs[@]}; do
    elements=( ${programs[$program]} )
    running_time_total=0
    counter=0

    while read -r line; do
        log=( $line )

        if [[ "${log[*]}" == *"Open"* ]]; then
            start_time=${log[2]}
            (( counter++ ))
        else
            finish_time=${log[2]}
            running_time_total=$(( $running_time_total + $(( $finish_time - $start_time )) ))
        fi
    
    done < <( grep ^[0-9]*' '"${elements[0]}" test_logs )

    programs[$program]="${elements[0]} $(( ${elements[1]} + $counter )) $(( ${elements[2]} + $running_time_total ))"

done
